version: '3.8'
services:
  php-apache-environment:
      container_name: oldyoungAPP
      build:
          context: ./seminaire_pdo
          dockerfile: dockerfile
      depends_on:
          - database
      volumes:
          - ./seminaire_pdo:/var/www/html/
      ports:
          - 8000:80
  database:
      restart: always
      container_name: oldyoungDB
      build:
          context: ./mysql
          dockerfile: dockerfile
      ports: 
          - "9000:3306"
      environment:
          MYSQL_DATABASE: seminaire_db
          MYSQL_USER: userseminaire
          MYSQL_PASSWORD: passer
          MYSQL_ROOT_PASSWORD: passer
      volumes:
          - ./seminaire_db.sql:/docker-entrypoint-initdb.d
          - persistent:/var/lib/mysql
      networks:
          - default
  phpmyadmin:
      container_name: oldyoungDBMyAdmin
      image: phpmyadmin/phpmyadmin
      links: 
          - database:database
      ports:
          - 8001:80
      environment:
          MYSQL_USER: userseminaire
          MYSQL_PASSWORD: passer
          MYSQL_ROOT_PASSWORD: passer
volumes:
  persistent:
    